# Generated by Django 5.2 on 2025-05-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ondc', '0002_fullonsearch_fullonselect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullOnSelect',
        ),
    ]
