# Generated by Django 5.2 on 2025-05-13 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondc', '0004_selectsip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ondc.transaction')),
            ],
        ),
    ]
