# Generated by Django 5.2 on 2025-05-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondc', '0006_sipfulfillment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionid',
            name='transaction',
        ),
        migrations.AddField(
            model_name='submissionid',
            name='message_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
