# Generated by Django 5.2 on 2025-05-13 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondc', '0007_remove_submissionid_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionid',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ondc.transaction'),
            preserve_default=False,
        ),
    ]
