# Generated by Django 5.2 on 2025-05-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondc', '0008_submissionid_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionid',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
