# Generated by Django 5.2 on 2025-05-14 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondc', '0010_alter_submissionid_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionid',
            name='message_id',
            field=models.CharField(default='default123', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OnInitSIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_on_init', to='ondc.transaction')),
            ],
        ),
    ]
