# Generated by Django 5.2 on 2025-05-18 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondc', '0013_onstatus_onupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSubmisssion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('status_pay', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ondc.transaction')),
            ],
        ),
        migrations.DeleteModel(
            name='SIPFulfillment',
        ),
    ]
